from ..__init__ import BotType, LMType

__BOT_TO_LM = {
    BotType.W2V_GLOVE_DISTANCE_ASSOCIATOR : LMType.W2V_GLOVE_50,
    BotType.W2V_DISTANCE_ASSOCIATOR : LMType.W2V,
    BotType.GLOVE_50_DISTANCE_ASSOCIATOR : LMType.GLOVE_50,
    BotType.GLOVE_100_DISTANCE_ASSOCIATOR : LMType.GLOVE_100,
    BotType.GLOVE_200_DISTANCE_ASSOCIATOR : LMType.GLOVE_200,
    BotType.GLOVE_300_DISTANCE_ASSOCIATOR : LMType.GLOVE_300,
    BotType.CN_NB_DISTANCE_ASSOCIATOR : LMType.CN_NB,
    BotType.D2V_DISTANCE_ASSOCIATOR : LMType.D2V,
    BotType.ELMO_DISTANCE_ASSOCIATOR : LMType.ELMO,
    BotType.BERT1_DISTANCE_ASSOCIATOR : LMType.BERT1,
    BotType.BERT2_DISTANCE_ASSOCIATOR : LMType.BERT2,
    BotType.FAST_TEXT_DISTANCE_ASSOCIATOR : LMType.FAST_TEXT,

    BotType.W2V_BASELINE_GUESSER : LMType.W2V,
    BotType.GLOVE_50_BASELINE_GUESSER : LMType.GLOVE_50,
    BotType.GLOVE_100_BASELINE_GUESSER : LMType.GLOVE_100,
    BotType.GLOVE_200_BASELINE_GUESSER : LMType.GLOVE_200,
    BotType.GLOVE_300_BASELINE_GUESSER : LMType.GLOVE_300,
    BotType.W2V_GLOVE_BASELINE_GUESSER : LMType.W2V_GLOVE_50, 
    BotType.CN_NB_BASELINE_GUESSER : LMType.CN_NB, 
    BotType.D2V_BASELINE_GUESSER : LMType.D2V,
    BotType.ELMO_BASELINE_GUESSER : LMType.ELMO,
    BotType.BERT1_BASELINE_GUESSER : LMType.BERT1,
    BotType.BERT2_BASELINE_GUESSER : LMType.BERT2,
    BotType.FAST_TEXT_BASELINE_GUESSER : LMType.FAST_TEXT,

    BotType.NOISY_DISTANCE_ASSOCIATOR : LMType.NOISY,
    BotType.NOISY_BASELINE_GUESSER : LMType.NOISY,

    BotType.DISTANCE_ENSEMBLE_CODEMASTER : LMType.ENSEMBLE,
    BotType.DISTANCE_ENSEMBLE_GUESSER : LMType.ENSEMBLE,

    BotType.RANDOM_DISTANCE_ENSEMBLE_CODEMASTER: LMType.RANDOM_ENSEMBLE,
    BotType.RANDOM_DISTANCE_ENSEMBLE_GUESSER: LMType.RANDOM_ENSEMBLE,
}

def getBotDict():
    return __BOT_TO_LM



def get_lm(bot_type_key):
    return __BOT_TO_LM.get(bot_type_key, LMType.NONE)